---
title: "data_prep_PreReg"
author: "Kathrin Reichmann"
date: "6 5 2021"
input: "data of experiment 1a"
output:
  html_document: default
  pdf_document: default
  csv:   "direct.csv, indirect.csv, drm.csv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstraction Mechanisms predict Generalization in EC - Study 1a (Chinese Characters), Data Preparation

Data preparation for analysis


```{r load libraries and clean the environment, echo=FALSE, include=FALSE}
library(dplyr)
library(tidyverse)
rm(list = ls())

```

```{r set local directory, echo=FALSE, include=FALSE}

localGitDir <- "C:/Users/reich/Documents/GitHub/CSCond_analysis/Study3a_chinese"

```

```{r read files, echo = FALSE}
filenames <- dir(paste (localGitDir, "/data", sep = ""))
dat <- data.frame()
for (i in filenames){
  dat <- rbind(dat, read.table( paste(localGitDir,"/data/", i , sep = ""),
                                header = TRUE, 
                                sep = ",", 
                                encoding = "UTF-8"))
}
rm (filenames, i)

```

```{r check number of conditions}

#prep
dat$subject <- factor(dat$subject)
dat$response <- as.numeric(dat$response)

#condition
get_tables <- aggregate(response ~ subject + condition, dat, mean)
table(get_tables$condition)

```

## Data Exclusion

```{r exclusion of data sets, echo = FALSE}
#total number of subjects before data exclusion
length(unique(dat$subject))

#chinese speaking participants
#0 = ja, 2 = keine Angabe
get_tables <- aggregate(response ~ subject + chinese, dat, mean)
table(get_tables$chinese)
dat <- dat[!dat$chinese == 0,]
dat <- dat[!dat$chinese == 2,]

#participants who did not pay attention
get_tables <- aggregate(response ~ subject + hinschauen, dat, mean)
table(get_tables$hinschauen) #1 = nicht hinschauen
dat <- dat[!dat$hinschauen == 1,]

#who were distracted
get_tables <- aggregate(response ~ subject + ablenkung, dat, mean)
table(get_tables$ablenkung) # 0 = abgelenkt
dat <- dat[!dat$ablenkung == 0,]

#who did not follow instructions
get_tables <- aggregate(response ~ subject + gewissenhaft, dat, mean)
table(get_tables$gewissenhaft) # 1 = nicht gewissenhaft

#total number of subjects after data exclusion
length(unique(dat$subject))

```

## Demgraphics

```{r demographic data, echo = FALSE}

#demographics before data exclusion
demographics <- dat[c('subject', 'age', 'gender', 'education', 'chinese', 'handedness')]
demographics <- aggregate(. ~ subject, demographics, median);


#education
table(demographics$education)
#1	Studierende/r
#2	Berufstätig
#3	Arbeitssuchend
#4	keine Angabe

##gender
table(demographics$gender)
#0	weiblich
#1	männlich
#2	divers
#3	keine Angabe

summary(demographics$age)

```

```{r general data preparation, echo = FALSE}


#delete unnessessary columns
#data.frame(colnames(dat))
dat[,1:5] <- NULL
dat$codeword <- NULL
dat$url <- NULL

#as factor
as_factor <- c("subject", "val", "condition_code", "condition", "measure", "measure_code", "type", "type_specific", "category", "cs_selected")

#rename stimulus names
as.factor(gsub(".png$", "", dat$target))-> dat$target
as.factor(gsub("targets/", "", dat$target))-> dat$target
as.factor(gsub(".png$", "", dat$cs_selected))-> dat$cs_selected
as.factor(gsub("category", "", dat$cs_selected))-> dat$cs_selected

```


## Direct Measure


```{r export data for direct measure, echo = FALSE}
#extract relevant columns
direct <- dat[dat$task == "direct" | dat$task == "all",] 
direct <- direct[c('response', 'subject', 'condition', 'condition_code', 'measure', 'measure_code', 'val', 'type', 'type_specific', 'category', 'cs_selected')]

for (factor in as_factor){
  direct[, factor] <- as.factor(direct[,factor])
}

direct$type_specific <- factor(direct$type_specific, levels = c('CS', 'GSold', 'GSnew', 'abstract', 'all'), labels = c('CS', 'GS same', 'GS different', "Feature", "Group"))
direct$response <- as.numeric(direct$response)
str(direct)

unique(direct$subject)

#export files
#setwd("\\\\sn00.zdv.uni-tuebingen.de/siskr01/Documents/Github/CSCond_analysis/CSCond_analysis/data")
setwd("C:/Users/reich/Documents/GitHub/CSCond_analysis/Study3a_chinese/data_preprocessed")
write.csv2(direct, file = 'direct.csv')

```


## Indirect Measure

```{r export data for indirect measurek, echo = FALSE}
#extract relevant columns
indirect <- dat[dat$task == "indirect",]
indirect <- indirect[c('indirect', 'rt', 'subject', 'condition', 'condition_code', 'measure', 'measure_code', 'val', 'type', 'type_specific', 'category', 'cs_selected', 'target', 'nr_pres')]

as_factor <- append(as_factor, "target")
for (factor in as_factor){
  indirect[, factor] <- as.factor(indirect[,factor])
}

indirect$response <- as.numeric(indirect$indirect)
indirect$indirect <- NULL
indirect$nr_pres <- as.numeric(indirect$nr_pres)
indirect$rt <- as.numeric(indirect$rt)
str(indirect)

indirect$type_specific <- factor(indirect$type_specific, levels = c('CS', 'GSold', 'GSnew', 'abstract'), labels = c('CS', 'GS same', 'GS different', "Feature"))

#export files
#setwd("\\\\sn00.zdv.uni-tuebingen.de/siskr01/Documents/Github/CSCond_analysis/CSCond_analysis/data")
setwd("C:/Users/reich/Documents/GitHub/CSCond_analysis/Study3a_chinese/data")
write.csv2(indirect, file = 'indirect.csv')

```

## DRM

```{r export data for DRM}



```

